Build native libs for linux-musl-arm and linux-musl-arm64
libgit2/libgit2sharp.nativebinaries pull request #130
Opened 2021-10-21 16:21 UTC by arturcic

Made the docker files use base images from multiarch/crossbuild and multiarch/alpine to make it easier to maintain.

Added support for linux-musl-arm and linux-musl-arm64.

Publishing the resulted nuget package only when it's manually run the workflow to GitHub Packages. (This allows to have the nuget package available to be consumed in other repository - libgit2sharp for example). I have a fork of libgit2sharp that does test the native libs with libgit2sharp on multiple linux distros and arm64/amd64 (check this out https://github.com/arturcic/libgit2sharp/actions/runs/1366916943). If this one gets merged I will also submit a PR to the libgit2sharp repo to include that worflow as well

2021-10-30 23:32 UTC, bording requested changes

2021-10-30 23:32 UTC, bording commented on .devcontainer/devcontainer.json
> +{
I'd prefer to keep the PR focused on just the required changes for the new libs, so let's get rid of this.

2021-10-30 23:32 UTC, bording commented on .github/workflows/ci.yml
> +      - name: Setup QEMU
What is this for?

2021-10-30 23:32 UTC, bording commented on .github/workflows/ci.yml
> +      - name: Publish nuget to GitHub Packages
Let's remove this. I don't immediately see a need for it, and it's not required to get the new libs building.

2021-10-30 23:32 UTC, bording commented on build.libgit2.sh
> +cmake --build . --config Release -- -j 16
What is this change doing?

2021-10-30 23:32 UTC, bording commented on Dockerfile.linux
> +FROM multiarch/crossbuild
I'm not really familiar with this. Can you explain a bit about how it works?

What distro is it based on? How do I know what version of libraries and tooling it comes with?

What if we need to add something that's not part of the base image? Does it have a package manager? For example, looking at the build output compared to older CI runs, it appears that `pkg-config` is not installed, and that's something that we had installed previously since libgit2 can use it to configure the build process.

The larger overall concern here is that in the past it's been a balancing act choosing which distro to use to build the `linux-x64` lib because it needs to have versions of all the libraries/tooling old enough that it will be compatible with all the various linux distros that .NET Core supports.

2021-10-30 23:32 UTC, bording commented on build.libgit2.sh
> -if [[ $RID == "" ]]; then
Why was this section removed?

2021-10-30 23:32 UTC, bording commented on dockerbuild.sh
> +docker buildx build -t $RID -f $dockerfile --build-arg ARCH=$arch .
What's the benefit/reason for using `buildx` vs `build`?

2021-10-30 23:34 UTC, bording commented
In addition to the comments above, I noticed that you open this PR against the `master` branch of your fork. Would it be possible to instead create a branch and open a new PR using that instead?

2021-10-31 00:52 UTC, ethomson commented on build.libgit2.sh
> +cmake --build . --config Release -- -j 16
I don't know if the release configuration is necessary.  (If we're not building release we probably should.)  But `--parallel` is much more portable than `-- -j 16`

2021-10-31 01:26 UTC, bording commented on build.libgit2.sh
> +cmake --build . --config Release -- -j 16
> I don't know if the release configuration is necessary. (If we're not building release we probably should.) But `--parallel` is much more portable than `-- -j 16`

`-DCMAKE_BUILD_TYPE:STRING=Release` Should be building release already, unless there's something I don't understand about cmake (which is entirely possible!)

2021-11-01 13:25 UTC, arturcic commented on .devcontainer/devcontainer.json
> +{
Do you think I should create a separate PR for this one? I did the entire PR with the codespaces and this was the configuration

2021-11-01 13:28 UTC, arturcic commented on .github/workflows/ci.yml
> +      - name: Setup QEMU
This one is use to install the qemu on the docker host to allow to build/run docker images for arm/arm64, needed to build the arm/arm64 images for alpine

2021-11-01 13:28 UTC, arturcic commented on build.libgit2.sh
> +cmake --build . --config Release -- -j 16
I will check the `--parallel` flag

2021-11-01 13:41 UTC, arturcic commented on Dockerfile.linux
> +FROM multiarch/crossbuild
[Here ](https://github.com/multiarch/crossbuild/blob/master/Dockerfile) is the Dockerfile for `multiarch/crossbuild`.
As you can see its base image is `buildpack-deps:stretch-curl`. Is that old enough you can tell me.


The native artifacts I tested with these docker images https://github.com/arturcic/libgit2sharp/actions/runs/1375914780 - both amd64 and arm64. The exact same images I use to test GitVersion. As you can see it's tested with .netcoreapp 3.1 up to net 6.0 with some exceptions - https://github.com/arturcic/libgit2sharp/blob/5dc30c137586583dea54716f866966c3089b3ddd/.github/workflows/native-test.yml#L18

From the tests were excluded the arm64 tests for alpine 3.12, and for alpine 3.13-3.14 for netcoreapp3.1, as .net is not supported on this ones.

As far as I know (tell me if I'm wrong) .net core 3.1 is the latest supported version of .net core at the moment. .net core 2.1 ended support this august. 
 So  took [this](https://github.com/dotnet/core/blob/main/release-notes/3.1/3.1-supported-os.md) in consideration when testing the native libs.

2021-11-01 13:44 UTC, arturcic commented on .github/workflows/ci.yml
> +      - name: Publish nuget to GitHub Packages
I needed a way to test the native libs without having to build locally on the dev machine, and it is used in the https://github.com/arturcic/libgit2sharp/actions/runs/1375914780 and it's a common practice I've seen on other dotnet repos to publish the nuget package previews on a nuget feed (previously myget, nowadays GH packages), but I can remove that if you don't think it's needed

2021-11-01 13:50 UTC, arturcic commented on dockerbuild.sh
> +docker buildx build -t $RID -f $dockerfile --build-arg ARCH=$arch .
This is needed to be able to build the alpine arm images (needed for qemu) and it can run in parallel stages in a staged Dockerfile (not this case though). It also allows to build multi-platform images if needed in one build command. 

`buildx` uses the same arguments as `build` so it can be easily changed.

2021-11-01 13:59 UTC, arturcic commented on build.libgit2.sh
> -if [[ $RID == "" ]]; then
2 reasons.

- in the build workflow https://github.com/libgit2/libgit2sharp.nativebinaries/blob/master/.github/workflows/ci.yml I saw that every `RID` was explicitly specified, not inferred. 
-  there is no supported targets for `unix-x64` or `unix-x86` in the [supported-targets](https://github.com/multiarch/crossbuild#supported-targets). We could change that to a supported one like `linux` or any one you consider as default.

2021-11-01 14:07 UTC, arturcic commented on Dockerfile.linux
> +FROM multiarch/crossbuild
> What if we need to add something that's not part of the base image?

Sure we can install any needed lib on top of that `multiarch/crossbuild` image

2021-11-01 14:08 UTC, arturcic commented on .github/workflows/ci.yml
> +      - name: Setup QEMU
I borrowed this one from [here](https://github.com/libgit2/libgit2/blob/358a60e1b46000ea99ef10b4dd709e92f75ff74b/.github/workflows/main.yml#L220)

2021-11-01 14:55 UTC, arturcic commented
> In addition to the comments above, I noticed that you open this PR against the `master` branch of your fork. Would it be possible to instead create a branch and open a new PR using that instead?

I close this PR in favor of https://github.com/libgit2/libgit2sharp.nativebinaries/pull/133

2021-11-01 14:55 UTC, closed without merging