Add MacOS Arm64 support
libgit2/libgit2sharp.nativebinaries pull request #131
Opened 2021-10-30 03:01 UTC by drasticactions

This edits the scripts and yaml to include a `osx-arm64` target. This should add the correct dylib to the Nuget package to be consumed by the main libgit2 library.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/898335/139518045-71e59661-f1db-4978-bba9-cbaf334d38ac.png">

2021-10-30 23:51 UTC, bording requested changes
Overall this looks good, just a few tweaks needed.

Also, I see that you opened the PR against the `master` branch of your fork. Would it be possible to create a branch and open a new PR from that instead?

That will also give you a chance to remove/clean up the unneeded intermediate commits you've got in here.

2021-10-30 23:51 UTC, bording commented on .github/workflows/ci.yml
> +          - os: macos-11
Unless there's a reason why we have to move to `macos-11` for this, I'd prefer to stick to `macos-10.15` for now. .NET Core 3.1 and .NET 6 both support older versions, so I think it makes sense to compile on the oldest version GitHub Actions has available.

2021-10-30 23:51 UTC, bording commented on UpdateLibgit2ToSha.ps1
> +    <dllmap os="osx" cpu="arm64" wordsize="64" dll="$binaryFilename" target="lib/osx-arm64/lib$binaryFilename.dylib" />
This file is for mono support, so I believe it needs to be:

```suggestion
    <dllmap os="osx" cpu="armv8" wordsize="64" dll="$binaryFilename" target="lib/osx-arm64/lib$binaryFilename.dylib" />
```

2021-10-30 23:51 UTC, bording commented on nuget.package/libgit2/LibGit2Sharp.dll.config
> +    <dllmap os="osx" cpu="arm64" wordsize="64" dll="git2-b7bad55" target="lib/osx-arm64/libgit2-b7bad55.dylib" />
```suggestion
    <dllmap os="osx" cpu="armv8" wordsize="64" dll="git2-b7bad55" target="lib/osx-arm64/libgit2-b7bad55.dylib" />
```

2021-10-30 23:51 UTC, bording commented on build.libgit2.sh
> +DCMAKEOSXARCHITECTURES="x86_64"
Let's name this `OSXARCHITECTURE` instead.

2021-10-30 23:51 UTC, bording commented on build.libgit2.sh
> +    DCMAKEOSXARCHITECTURES="arm64"
Something seems off about this change. Setting `DCMAKEOSXARCHITECTURES` again seems redundant. We should be able to remove this and just keep the condition you added to make sure it's not set when on macOS.

2021-10-30 23:51 UTC, bording commented on build.libgit2.sh
> +cp libgit2/build/libgit2-$SHORTSHA.$LIBEXT $PACKAGEPATH/$RID/native
Nitpick, but let's add the newline back to the file.

2021-10-31 01:42 UTC, Therzok commented on .github/workflows/ci.yml
> +          - os: macos-11
Afaik, you need Big Sur to target ARM (Xcode 13 depends on Big Sur).

2021-10-31 05:00 UTC, drasticactions commented on .github/workflows/ci.yml
> +          - os: macos-11
Yeah, you need Big Sur to compile it for ARM64, since that's the first platform that really supports it anyway.

2021-10-31 05:01 UTC, drasticactions commented
Unnecessary commits doesn't really matter when they get squashed anyway, but I can make a new one.

2021-10-31 05:01 UTC, closed without merging

2021-10-31 05:10 UTC, drasticactions commented
New PR https://github.com/libgit2/libgit2sharp.nativebinaries/pull/132